packaging_format = 2

id = "lichenmarkdown"
name = "Lichen-Markdown"
description.en = "permacomputing cms"
description.fr = "permacomputing cms"

version = "3.7.0~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
admindoc = "https://lichen.commoninternet.net"
code = "https://codeberg.org/ukrudt.net/lichen-markdown/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin_password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://codeberg.org/ukrudt.net/lichen-markdown/archive/v1.0.0.zip"
        sha256 = "5711ae9db1e20456fbe45e8888da75531992b44237e44e1bf0d0cb507af81779"
        in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "apache2-utils php8.2-intl, php8.2-mysql, php8.2-gd, php8.2-fileinfo, php8.2-zip, php8.2-ldap"

