packaging_format = 2

id = "lichenmarkdown"
name = "Lichen-Markdown"
description.en = "permacomputing cms"
description.fr = "permacomputing cms"

version = "1.2.1~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
admindoc = "https://lichen.commoninternet.net"
code = "https://codeberg.org/ukrudt.net/lichen-markdown/"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin_password]
    type = "password"
    ask = "What password will you use to login to the admin section?"

[resources]
        [resources.sources.main]
        url = "https://codeberg.org/ukrudt.net/lichen-markdown/archive/v1.2.1.zip"
        sha256 = "9513becb18499fc7e0cc627ecc872df5b12ddaf569f04669dacd100daf21843c"
        in_subdir = false

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:rwx"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "apache2-utils php8.2-intl, php8.2-mysql, php8.2-gd, php8.2-fileinfo, php8.2-zip, php8.2-ldap, php8.2-fpm"

