#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=1G

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================

htpasswd -cb $install_dir/lichen-markdown/.htpasswd admin $admin_password

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
