#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
upgrade_temp_dir=$install_dir/upgrade
ynh_setup_source --dest_dir="$upgrade_temp_dir"

# upgrade only the lichen-markdown/src/cms folder
mv $install_dir/lichen-markdown/src/cms $upgrade_temp_dir/cms-backup
cp -r $upgrade_temp_dir/src/cms $install_dir/lichen-markdown/src/cms
ynh_secure_remove $upgrade_temp_dir

chown -R $app:www-data "$install_dir"
chmod -R u+rwX,g+rwX,o= "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
