#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=1G

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
upgrade_temp_dir=$install_dir/upgrade
ynh_setup_source --dest_dir="$upgrade_temp_dir"

# upgrade only the lichen-markdown/src/cms folder
mv $install_dir/lichen-markdown/src/cms $upgrade_temp_dir/cms-backup
cp -r $upgrade_temp_dir/lichen-markdown/src/cms $install_dir/lichen-markdown/src/cms
ynh_safe_rm $upgrade_temp_dir
chmod -R u+rwX,g+rwX,o= $install_dir/lichen-markdown/
chown -R $app:www-data $install_dir/lichen-markdown/

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading PHP-FPM configuration..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_script_progression "Configuring fail2ban..."
ynh_config_add_fail2ban --logpath="/var/log/nginx/$domain-error.log" --failregex='user ".*": password mismatch, client: <HOST>,'

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
